    //*** Italian TEMPLATE
  sCancelCaptionI = 'Annulla';
  CaptionsI: array[TMsgDlgType] of string = ('Attenzione', 'Errore',
    'Informazione', 'Conferma', '');

  ButtonCaptionsI: array[TMsgDlgBtn] of string = (
    'Si', 'No', 'OK', 'Annulla', 'Termina', 'Riprova', 'Ignora', 'Tutti',
    'No a tutti', 'Si a tutti', 'Aiuto!', '');

  //*** English TEMPLATE
  sCancelCaptionE = 'Cancel';
  CaptionsE: array[TMsgDlgType] of string = ('Warning', 'Error',
    'Information', 'Confirm', '');

  ButtonCaptionsE: array[TMsgDlgBtn] of string = (
    'Yes', 'No', 'OK', 'Cancel', 'Abort', 'Retry', 'Ignore', 'All',
    'No to all', 'Yes to all', 'Help', '');

  //*** Russian
  sCancelCaptionR = 'Отмена';
  CaptionsR: array[TMsgDlgType] of string = ('Предупреждение', 'Ошибка',
    'Информация', 'Подтверждение', '');

  ButtonCaptionsR: array[TMsgDlgBtn] of string = (
    'Да', 'Нет', 'OK', 'Отмена', 'Стоп', 'Повтор', 'Пропустить', 'Все',
    'Нет для всех', 'Да для всех', 'Справка', '');

  //*** Portuguese
  sCancelCaptionP = 'Cancela';
  CaptionsP: array[TMsgDlgType] of string = ('Aviso', 'Erro',
    'Informaзгo', 'Confirmaзгo', '');

  ButtonCaptionsP: array[TMsgDlgBtn] of string = (
    'Sim', 'Nгo', 'OK', 'Cancela', 'Aborta', 'Tenta Novamente', 'Ignora',
    'Tudo',
    'Nгo para Tudo', 'Sim para Tudo', 'Ajuda','');

  //*** Turkish
  sCancelCaptionT = 'Vazgeз';
  CaptionsT: array[TMsgDlgType] of string = ('Uyarэ', 'Hata',
    'Bilgi', 'Doрrulama', '');

  ButtonCaptionsT: array[TMsgDlgBtn] of string = (
    'Evet', 'Hayэr', 'TAMAM', 'Vazgeз', 'Durdur', 'Tekrar', 'Эptal', 'Hepsi',
    'Hepsine hayэr', 'Hepsine evet', 'Yardэm','');

  //*** German
  sCancelCaptionG = 'Abbrechen';
  CaptionsG: array[TMsgDlgType] of string = ('Warnung', 'Fehler',
    'Information', 'Bestдtigung', '');

  ButtonCaptionsG: array[TMsgDlgBtn] of string = (
    'Ja', 'Nein', 'OK', 'Abbrechen', 'Abbrechen', 'Wiederholen', 'Ignorieren',
    'Alle',
    'Nein zu allen', 'Ja zu allen', 'Hilfe','');


  //*** Dutch
  sCancelCaptionD = 'Annuleren';
  CaptionsD: array[TMsgDlgType] of string = ('Waarschuwing', 'Fout',
    'Informatie', 'Bevestiging', '');

  ButtonCaptionsD: array[TMsgDlgBtn] of string = (
    'Ja', 'Nee', 'OK', 'Annuleren', 'Afbreken', 'Herhalen', 'Negeren', 'Alles',
    'Nee op alles', 'Ja op alles', '?','');

  //*** French
  sCancelCaptionF = 'Annuler';
  CaptionsF: array[TMsgDlgType] of string = ('Avertissement', 'Erreur',
    'Information', 'Confirmation', '');

  ButtonCaptionsF: array[TMsgDlgBtn] of string = (
    'Oui', 'Non', 'OK', 'Annuler', 'Abandonner', 'Rйessayer', 'Ignorer', 'Tout',
    'Non pour tous', 'Oui pour tous', 'Aide', '');

  //*** Greek
  sCancelCaptionGr = 'ўкхсп';
  CaptionsGr: array[TMsgDlgType] of string = ('РспупчЮ!', 'ЛЬипт',
    'РлзспцпсЯб', 'ЕрйвевбЯщуз', '');

  ButtonCaptionsGr: array[TMsgDlgBtn] of string = (
    'НбЯ', 'јчй', 'ЕнфЬоей', 'ўкхсп', 'ўкэсщуз', 'РспурЬиейб', 'Бгнюзуз', 'јлб',
    'јчй уе ьлб', 'НбЯ уе ьлб', 'ВпЮиейб', '');

  //*** Spanish
  sCancelCaptionS = 'Cancelar';
  CaptionsS: array[TMsgDlgType] of string = ('Precauciуn', 'Error',
    'Informaciуn', 'Confirmaciуn', '');

  ButtonCaptionsS: array[TMsgDlgBtn] of string = (
    'Si', 'No', 'OK', 'Cancelar', 'Abortar', 'Reintentar', 'Ignorar', 'Todo',
    'No a todo', 'Si a todo', 'Ayuda', '');

